S30optee: Setting permissions for tee-supplicant on /dev/mmcblk*rpmb
If not, the supplicant cannot communicate with rpmb as it requires
root privileges

Signed-off-by: Timothée Cercueil <timothee.cercueil@st.com>

diff --git a/br-ext/package/optee_client_ext/S30optee b/br-ext/package/optee_client_ext/S30optee
--- a/br-ext/package/optee_client_ext/S30optee
+++ b/br-ext/package/optee_client_ext/S30optee
@@ -19,6 +19,17 @@ start() {
 		echo "FAIL"
 		return "$status"
 	fi
+
+    printf "Set permissions on all RPMB devices: "
+    chown root:tee /dev/mmcblk*rpmb && chmod 0660 /dev/mmcblk*rpmb
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+		return "$status"
+	fi
+
 	if [ -e /dev/ion ]; then
 		printf 'Set permissions on %s: ' "/dev/ion"
 		chown root:ion /dev/ion && chmod 0660 /dev/ion
